[build]
  base = "my-project"
  publish = "my-project/build"
  command = "npm ci && npm run build"

[functions]
  directory = "backend"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/netlify-handler/:splat"
  status = 200
  force = true


